fm_elfinder:
  assets_path: "/assets_admin"
  instances:
    default:
      locale: ru # defaults to current request locale
      editor: tinymce4 # other options are tinymce, tinymce4, form, custom and simple
      fullscreen: true # defaults true, applies to simple and ckeditor editors
      theme: smoothness # jquery theme
      include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
      connector:
        debug: false # defaults to false
        roots:       # at least one root must be defined
          uploads:
            show_hidden: false # defaults to false
            driver: LocalFileSystem
            path: "uploads/custom"
            upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
            upload_deny: ['all']
            upload_max_size: 16M