# Read the documentation: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md
oneup_uploader:
    mappings:
        images:
            frontend: blueimp
        avatars:
            frontend: blueimp
