sonata_admin:
    title: 'SYM'
    templates:
        layout:  admin\layout.html.twig
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]