stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    # Get current language from the parameters.ini
    language: ru
    theme:
        # Simple theme: same as default theme
        simple: ~
        # Advanced theme with almost all enabled plugins
        advanced:
            height: 400
            file_browser_callback : 'elFinderBrowser'
            menubar: false
            plugins:
                - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | code"
            toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
            image_advtab: true
            relative_urls: false
        mini:
            height: 150
            file_browser_callback : 'elFinderBrowser'
            menubar: false
            plugins:
                - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | code"
            toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
            image_advtab: true
            relative_urls: false