#!/bin/bash

cd verstka_src
gulp build
#cp -R dist/css ../src/AppBundle/Resources/public/
#cp -R dist/fonts ../src/AppBundle/Resources/public/
#cp -R dist/img ../src/AppBundle/Resources/public/
#cp -R dist/js ../src/AppBundle/Resources/public/
cd ..
