<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * BuyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get comments for my models
     *
     * @return array
     */
    public function getMyBuy(User $user)
    {
        $qb = $this->_baseQb();

        $qb
            ->andWhere('b.user = :user')
            ->setParameter('user', $user);

        return $qb->getQuery()->getResult();
    }

    private function _baseQb()
    {
        $qb = $this->createQueryBuilder('b')
            ->innerJoin('b.product', 'p');

        $qb
            ->andWhere('p.active = true')
            ->andWhere('p.moderated = true')
            ->andWhere('p.deleted = false')
            ->andWhere('p.block = false')
        ;

        return $qb;
    }
}
