<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get from category
     *
     * @return array
     */
    public function getByCategory($category, $sortArray)
    {
        $qb = $this->createQueryBuilder('p');

        $qb
            ->andWhere('p.category = :category OR p.category2 = :category OR p.category3 = :category OR p.category4 = :category OR p.category5 = :category')
            ->setParameter('category', $category)
            ->andWhere('p.active = true')
            ->andWhere('p.moderated = true')
            ->andWhere('p.deleted = false')
            ->andWhere('p.block = false')
        ;

        if(is_array($sortArray)){
            $keys = array_keys($sortArray);
            $values = array_values($sortArray);
            $qb->orderBy('p.'.$keys[0], $values[0]);
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * Get from category
     *
     * @return array
     */
    public function getByCategories($categories)
    {
        $qb = $this->createQueryBuilder('p');

        $qb
            ->andWhere('p.category IN (:categories)')
            ->setParameter('categories', $categories)
            ->andWhere('p.active = true')
            ->andWhere('p.moderated = true')
            ->andWhere('p.deleted = false')
            ->andWhere('p.block = false')
        ;


        $qb->orderBy('p.date', 'DESC');

        return $qb->getQuery()->getResult();
    }

    /**
     * Get by tag
     *
     * @return array
     */
    public function getByTag($tag)
    {
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.tags', 't');

        $qb
            ->andWhere('t.id = :tag')
            ->setParameter('tag', $tag)
            ->andWhere('p.active = true')
            ->andWhere('p.moderated = true')
            ->andWhere('p.deleted = false')
            ->andWhere('p.block = false')
        ;


        $qb->orderBy('p.date', 'DESC');

        return $qb->getQuery()->getResult();
    }

    /**
     * Get by tag
     *
     * @return array
     */
    public function getForModeration()
    {
        $qb = $this->createQueryBuilder('p');

        $qb
            ->andWhere('p.active = true')
            ->andWhere('p.moderated = false')
            ->andWhere('p.deleted = false')
            ->andWhere('p.block = false')
        ;


        $qb->orderBy('p.date', 'DESC');

        return $qb->getQuery()->getResult();
    }

    /**
     * Get sale items
     *
     * @return array
     */
    public function getSale()
    {
        return $this->createQueryBuilder('p')
            ->where('p.active = true')
            ->andWhere('p.discountPersent is not null')
            ->andWhere('p.discountPersent > :persent')
            ->setParameter('persent', 0)
            ->getQuery()
            ->getResult();
    }

    public function findLastPos($category = null)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('MAX(p.pos)');

        $qb->where('p.category = :category')
            ->setParameter('category', $category);

        return $qb->getQuery()
            ->getSingleScalarResult();
    }

    public function findLastPosInRoot()
    {
        $qb = $this->createQueryBuilder('p')
            ->select('MAX(p.pos)');

        $qb->where('p.category = :category')
            ->setParameter('category', NULL);

        return $qb->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * Find By Categories.
     *
     * @return array
     */
    public function getSearch($search, $limit = false)
    {

        $qb = $this->createQueryBuilder('p')
            ->select('p');

        if ($search) {

            $a = explode(' ',$search);

            for($i=0;$i<count($a);$i++){
                $qb->andWhere('p.name LIKE :search'.$i)
                    ->setParameter('search'.$i, '%'.$a[$i].'%');
            }
        }

        if($limit){
            $qb->setMaxResults($limit);
        }

        $qb->andWhere('p.active = true');

        return $qb->getQuery()
            ->getResult();
    }

    public function getByIds($ids)
    {
        return $this->createQueryBuilder('p')
            ->where('p.id IN (:ids)')
            ->setParameter('ids', array_values($ids))
            ->setMaxResults(20)
            ->getQuery()
            ->getResult();
    }

    public function getByIdsInCabinet($ids)
    {
        return $this->createQueryBuilder('p')
            ->where('p.id IN (:ids)')
            ->setParameter('ids', array_values($ids))
            ->getQuery()
            ->getResult();
    }

    public function getUpperObject($object){

        $qb = $this->createQueryBuilder('c')
            ->andWhere('c.pos > :pos')
            ->setParameter('pos',$object->getPos());

        if($object->getCategory()){
            $qb->andWhere('c.category = :category')
                ->setParameter('category',$object->getCategory());
        }
        else{
            $qb->andWhere('c.category IS NULL');
        }

        return $qb->orderBy('c.pos', 'ASC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

    }

    public function getDownObject($object){

        $qb = $this->createQueryBuilder('c')
            ->andWhere('c.pos < :pos')
            ->setParameter('pos',$object->getPos());

        if($object->getCategory()){
            $qb->andWhere('c.category = :category')
                ->setParameter('category',$object->getCategory());
        }
        else{
            $qb->andWhere('c.category IS NULL');
        }

        return $qb->orderBy('c.pos', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

    }
}
