<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Product;

/**
 * ResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get sale items
     *
     * @return array
     */
    public function findByProduct(Product $product)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('p.products', 'pr')
            ->where('p.active = true')
            ->andWhere('pr.product = :product')
            ->setParameter('product', $product)
            ->getQuery()
            ->getResult();
    }
}
