<?php

namespace AppBundle\Repository;

/**
 * TextPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextPageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get text pages, expect main page
     *
     * @return array
     */
    public function getPages()
    {
        return $this->createQueryBuilder('p')
            ->where('p.url <> :url')
            ->setParameter('url', '/')
            ->getQuery()
            ->getResult();
    }
}
