<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Check exist email in cabinet settings.
     *
     * @param string $profile
     *
     * @return User|null
     */
    public function getOneByUserAndEmail($user, $email)
    {
        return $this->createQueryBuilder('user')
            ->where('user.email = :email')
            ->andWhere('user.id <> :id')
            ->setParameter('email', $email)
            ->setParameter('id', $user->getId())
            ->getQuery()
            ->getOneOrNullResult();
    }
}
