imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata/main.yml }
    - { resource: sonata/media.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets:
        version: "v20170228"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'AppBundle:Admin:sonata_model_form.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [AppBundle,FOSUserBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        schema_filter: ~^(?!t_)~
        types:
                json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            sale_filter:
                class:   AppBundle\Filter\SaleFilter
            available_filter:
                class:   AppBundle\Filter\AvailableFilter
            corner_filter:
                class:   AppBundle\Filter\CornerFilter
            scatter_filter:
                class:   AppBundle\Filter\ScatterFilter
            leather_filter:
                class:   AppBundle\Filter\LeatherFilter
            fabric_filter:
                class:   AppBundle\Filter\FabricFilter
            price_filter:
                class:   AppBundle\Filter\PriceFilter

fos_user:
  db_driver:  orm # can be orm or odm
  firewall_name:  main
  user_class:  AppBundle\Entity\User
  from_email:
          address:        "info@imodern.ru"
          sender_name:    "iModern"
  resetting:
          token_ttl: 600

hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    connect:
        account_connector: app_provider
        confirmation: false
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            #facebook: facebook_id
            vkontakte: vkontakte_id
            #mailru: mailru_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_app_id%"
            client_secret:       "%facebook_app_secret%"
            scope:               "email,public_profile"
            infos_url:     "https://graph.facebook.com/me?fields=id,email,birthday,link,name,gender,picture.type(small)"
            options:
                display: popup
        vkontakte:
            type:                vkontakte
            client_id:           "%vkontakte_app_id%"
            client_secret:       "%vkontakte_app_secret%"
        google:
            type:                odnoklassniki
            client_id:           "%odnoklassniki_app_id%"
            client_secret:       "%odnoklassniki_app_secret%"
            options:
                application_key: "%odnoklassniki_app_key%"
    # here you will add one (or more) configurations for resource owners

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_elastica:
    clients:
        default: { host: '127.0.0.1', port: 9200 }
    indexes:
        app:
            index_name: app_%kernel.environment%
            types:
                catalog:
                    mappings:
                        name: ~
                        manufacturer: ~
                        tags: ~
                        text: ~
                    persistence:
                        # the driver can be orm, mongodb, phpcr or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: AppBundle\Entity\Product
                        provider: ~
                        finder: ~

white_october_breadcrumbs: ~

stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    # Get current language from the parameters.ini
    language: ru
    theme:
        # Simple theme: same as default theme
        simple: ~
        # Advanced theme with almost all enabled plugins
        advanced:
             height: 400
             file_browser_callback : 'elFinderBrowser'
             menubar: false
             plugins:
                 - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                 - "searchreplace wordcount visualblocks visualchars code fullscreen"
                 - "insertdatetime media nonbreaking save table contextmenu directionality"
                 - "emoticons template paste textcolor"
             toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | code"
             toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
             image_advtab: true
        mini:
             height: 150
             file_browser_callback : 'elFinderBrowser'
             menubar: false
             plugins:
                 - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                 - "searchreplace wordcount visualblocks visualchars code fullscreen"
                 - "insertdatetime media nonbreaking save table contextmenu directionality"
                 - "emoticons template paste textcolor"
             toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | code"
             toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
             image_advtab: true

fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: tinymce4 # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: "uploads/custom"
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 16M

oneup_uploader:
    chunks:
        maxage:               604800
        storage:
            type:               filesystem
            directory:          ~
            filesystem:         ~
            sync_buffer_size:   100K
            stream_wrapper:     ~
            prefix:             'chunks'
        load_distribution:    true
    mappings:
        images:
            frontend: blueimp
        avatars:
            frontend: blueimp