# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                #csrf_provider: security.csrf.token_manager
                success_handler: wp_authentication_handler
                failure_handler: wp_authentication_handler
                require_previous_session: false
            logout:       true
            anonymous:    true
            switch_user:  true
            remember_me:
                key:      '%secret%'
                lifetime: 2592000 # 30 days in seconds
                path:     /
                always_remember_me: true
            oauth:
                resource_owners:
                     facebook:           "/login/check-facebook"
                     vkontakte:          "/login/check-vkontakte"
                     google:             "/login/check-google"
                login_path:        /login
                failure_path:      /login

                oauth_user_provider:
                     #this is my custom user provider, created from FOSUBUserProvider - will manage the
                     #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                     service: app_provider

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/catalog/add/, role: ROLE_USER }
        - { path: ^/cabinet/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }
