<?php

namespace App\Repository;
use App\Entity\User;

/**
 * ProductFavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductFavoriteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get comments for my models
     *
     * @return array
     */
    public function getMyFavorites(User $user)
    {
        $qb = $this->_baseQb();

        $qb
            ->andWhere('f.user = :user')
            ->setParameter('user', $user);

        return $qb->getQuery()->getResult();
    }

    private function _baseQb()
    {
        $qb = $this->createQueryBuilder('f')
            ->innerJoin('f.product', 'p');

        $qb
            ->andWhere('p.active = true')
            ->andWhere('p.moderated = true')
            ->andWhere('p.deleted = false')
            ->andWhere('p.block = false')
        ;

        return $qb;
    }
}
