<?php

namespace App\Repository;
use App\Entity\Product;

/**
 * SoftwareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftwareRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get sale items
     *
     * @return array
     */
    public function findForStats()
    {
        return $this->createQueryBuilder('s')
            ->where('s.active = true')
            ->andWhere('s.count > 0')
            ->getQuery()
            ->getResult();
    }
}
