<?php

namespace App\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Check exist email in cabinet settings.
     *
     * @param string $profile
     *
     * @return User|null
     */
    public function getOneByUserAndEmail($user, $email)
    {
        return $this->createQueryBuilder('user')
            ->where('user.email = :email')
            ->andWhere('user.id <> :id')
            ->setParameter('email', $email)
            ->setParameter('id', $user->getId())
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @return array
     */
    public function findNotConfirmedEmails()
    {

        $qb = $this->createQueryBuilder('u');

        $date = new \DateTime();
        $date->modify("-1 day");

        $qb->andWhere('u.emailNeedCheck = :emailNeedCheck')
            ->setParameter('emailNeedCheck', true)
        ;

        $qb->andWhere('u.emailConfirm = :emailConfirm')
            ->setParameter('emailConfirm', false)
        ;

        $qb->andWhere('u.createdAt < :date')
            ->setParameter('date', $date);

        return $qb->getQuery()
            ->getResult();
    }

    /**
     * @return array
     */
    public function findAdmins()
    {

        $qb = $this->createQueryBuilder('u');

        $qb->andWhere('u.accessTracker = :accessTracker')
            ->setParameter('accessTracker', true)
        ;

        $qb->addOrderBy('u.name', 'ASC');

        return $qb->getQuery()
            ->getResult();
    }
}
