sonata_media:

    providers:
        image:
            resizer:    sonata.media.resizer.cut # sonata.media.resizer.square

    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                #- sonata.media.provider.dailymotion
                #- sonata.media.provider.youtube
                - sonata.media.provider.image
                #- sonata.media.provider.file
                #- sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        slider:
            providers:
                - sonata.media.provider.image

            formats:
                full:   { width: 1190 , height: 470, quality: 100}
        informImage:
            providers:
                - sonata.media.provider.image

            formats:
                full:   { width: 367 , height: 232 , quality: 100}
        informImageBottom:
            providers:
                - sonata.media.provider.image

            formats:
                full:   { width: 1190 , height: 100 , quality: 100}
        informImageRight:
            providers:
                - sonata.media.provider.image

            formats:
                full:   { width: 230 , height: 550 , quality: 100}
        articles:
            providers:
                - sonata.media.provider.image

            formats:
                big:   { width: 916, height: 169 , quality: 100}
                full:   { width: 1600 , quality: 100}
        product:
            providers:
                - sonata.media.provider.image

            formats:
                small:   { width: 123, height: 123 , quality: 100}
                big:   { width: 228, height: 179 , quality: 100}
                full:   { width: 600 , height: 600, quality: 100}
        avatar:
            providers:
                - sonata.media.provider.image

            formats:
                small:   { width: 32, height: 32 , quality: 100}
                big:   { width: 100, height: 100 , quality: 100}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     true