#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_extra:
  resource: .
  type: extra

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

oneup_uploader:
  resource: .
  type: uploader